BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBB 
    
BBBBBBBBBBBBB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
            XXXX XXXX XXXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXX XXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                XXXX XXXX XXXXXXX XXX
                XX XXXXXXXXXXXXXXXXX XX XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB