XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXX XXXXXXXX XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXXX
    XXXXXXXXXXXXXXXX X BBBBB BBBBBBBBBBBXXBBBBBBBBXXXXXXXX
XXXXXXX
XXXXXX
    BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
             
        BBBBBB
    BBBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXX
        BBBB BBBB
        BBBB BBBBBB
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX
    XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX    
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBB B B
                     gettext(u'Koszyk:') 
                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                         gettext(u'\n                        %(total_items)s item%(total_items_plural)s,%(total_price)s zł\n                    ') 
                        SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS
                    
                    XXXX
                BBBB
                     gettext(u'Koszyk jest pusty.') 
                BBBBB
            BBBBBBB
        XXXXX
        XXXXX
    XXXXXX
XXXXXX
BBBBB BBBBBBBBBBBB

BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX