BBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBB 
    XXXX 
BBBBBBBBBBBBB BBBBBBBBBBBB
    BBB BBBBBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX    
                XXXX XXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    BBBBB
        XXXXXXXXX XX XXXXXXXX XXXX XXXX XXXXXXX XXXXXXXX
    BBBBBB
BBBBBBBB