BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBB 
    XXXXX 
BBBBBBBB
BBBBB BBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
	    
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX 

BBBBBBBB