# Generated by Django 3.2.3 on 2021-05-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
