BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBB
    XXXXXXXXX XXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBB

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB